project:
  type: website
  output-dir: docs
  twitter-card:
    creator: "@phdemetri"

website:
  title: "PhDemetri"
  site-url: https://dpananos.github.io/
  description: Numbers, Letters, Sometimes Both
  navbar:
    right:
      - about.qmd
      - consulting.qmd
      - icon: github
        href: https://github.com/Dpananos
      - icon: twitter
        href: https://twitter.com/PhDemetri
      - icon: linkedin
        href: https://www.linkedin.com/in/demetripananos/
      - icon: rss
        href: index.xml
  search:
    location: navbar
    type: overlay
format:
  html:
    theme: flatly
    css: styles.css



